# Generated by Django 5.2.5 on 2025-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('client', 'Клиент'), ('landlord', 'Арендодатель'), ('admin', 'Администратор'), ('superuser', 'Суперпользователь')], default='client', max_length=30, verbose_name='Роль'),
        ),
    ]
