# Generated by Django 5.1.4 on 2025-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
