# Generated by Django 5.2.5 on 2025-10-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Темная'), ('light', 'Светлая')], default='dark', max_length=10, verbose_name='Тема'),
        ),
    ]
