# Generated by Django 5.2.5 on 2025-09-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('hourly', 'Почасовая'), ('daily', 'Посуточная')], max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Motocycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=128, verbose_name='Название мотоцикла')),
                ('model', models.CharField(max_length=128, verbose_name='Модель')),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('sport', 'Спортивный'), ('naked', 'Классический'), ('touring', 'Туристический'), ('cruiser', 'Круизер'), ('enduro', 'Эндуро')], max_length=50)),
                ('engine_volume', models.PositiveIntegerField(default='50')),
                ('power', models.PositiveIntegerField(default='10')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('electric', 'Электро')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат')], default='manual', max_length=20)),
                ('weight', models.PositiveIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена в день')),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('min_rental_hours', models.PositiveIntegerField(default=4)),
                ('min_rental_days', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorcycles/')),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RentalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comment', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
