# Generated by Django 5.2.5 on 2025-09-13 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motocycles'),
        ),
        migrations.AddField(
            model_name='photo',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.motocycles'),
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_periods', to='api.motocycles'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.rentalperiod'),
        ),
        migrations.AddField(
            model_name='review',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motocycles'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('motorcycle',), name='unique_primary_photo_per_motorcycle'),
        ),
        migrations.AddIndex(
            model_name='rentalperiod',
            index=models.Index(fields=['start_time', 'end_time'], name='api_rentalp_start_t_bdd33c_idx'),
        ),
    ]
