# Generated by Django 5.2.5 on 2025-10-03 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motocycles',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный (в общем каталоге)'),
        ),
        migrations.AddField(
            model_name='motocycles',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_motorcycles', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
