# Generated by Django 5.2.5 on 2025-09-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-is_primary', 'id']},
        ),
        migrations.AddField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.motocycles'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('motorcycle',), name='unique_primary_photo_per_motorcycle'),
        ),
    ]
